FROM mcr.microsoft.com/devcontainers/rust

ARG USER_NAME

RUN \
  # Update container user
  groupmod -n ${USER_NAME} vscode && \
  usermod -l ${USER_NAME} vscode && \
  usermod -d /home/${USER_NAME} -m ${USER_NAME} && \

  # Persist bash history
  SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" && \
  mkdir /commandhistory && \
  touch /commandhistory/.bash_history && \
  chown -R ${USER_NAME} /commandhistory && \
  echo "$SNIPPET" >> "/home/${USER_NAME}/.bashrc"

USER ${USER_NAME}
